### ISSUE TITLE
`build.zig.zon` with inexistent git repo

### ISSUE THREAD

**Issue by Ev1lT3rm1nal** [kassane/zig-xlsxwriter#2]
The url provided in the build.zig.zon of [libxlsxwriter](https://github.com/kassane/zig-xlsxwriter/archive/c32228725fb36a05e8bae52857e926d209cb0530.tar.gz) does not exist, so the project cannot be compiled

**Comment by kassane** [comment]
@Ev1lT3rm1nal, fixed!! Using official dependency https://github.com/jmcnamara/libxlsxwriter/blob/main/build.zig
